### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JohnnyPicnic**
It took me a while to figure out I had to change my DNS server to point to my HASSIO's IP. 
I just suggest adding the one line to the instructions to help others out.

### CODE REVIEW

**Comment by frenck** [comment]
IMHO this is not the recommended (my personally preferred) way, but it is a method.

The problem with describing this part is that there are tons of methods to set this up.

**Comment by JohnnyPicnic** [comment]
Maybe i’m not using the add-on correctly? Without pointing a device to the Adguard server how else would you use it?

**Comment by frenck** [comment]
You could add it to your router or other existing DHCP server.
You can turn off the DHCP server you currently have and use the one provided by AdGuard
you can use adguard as an upstream dns server
or even change DNS setting on each device manually...

(and a couple of more options).

**Comment by frenck** [comment]
I'm not adding this, to prevent these kinds of discussions. If someone starts changing their network, they should know what they are doing.

**Pull request closed without merging**
