### PR TITLE
Remove content type

### PR DESCRIPTION
**Pull request by snapsl**
# Proposed Changes

remove nginx content type

## Related Issues

#359

### CODE REVIEW

**Comment by sinclairpaul** [comment]
Interested to know the testing done here, as from my testing if you expose the WebUI via a port the problem doesn't occur.  As the nginx config is shared, not sure how this fixes the issue?

**Comment by snapsl** [comment]
@sinclairpaul You are right, this will not fix the issue.
Is it an option to set a proxy header in `proxy_params.conf`?
E.g. `proxy_set_header Accept_Encoding "";`

**Comment by sinclairpaul** [comment]
In summary no, as some of the API calls require application/json (you can see that in the release notes as well).

I really think this needs to be resolved at the supervisor layer.

**Comment by snapsl** [comment]
Closed

**Pull request closed without merging**
