### PR TITLE
Add ports for DNS protocols DoH, DoQ, DoT

### PR DESCRIPTION
**Pull request by imbenwolf**
# Proposed Changes

> Adding ports for DoH, DoQ, DoT

## Related Issues

> dunno

### CODE REVIEW

**Comment by frenck** [comment]
How would this work?

**Comment by imbenwolf** [comment]
> How would this work?

Adguard has the Encryption option which exposes these ports. I thought this way you could map your own ports to work alongside proxies like NGINX and forward the ports from the router. This would enable DoH etc. from outside the network and would be useful for privacy purposes

**Comment by frenck** [comment]
Yeah, but uh... this add-on runs on the host network, so... I don't get it?

**Comment by imbenwolf** [comment]
oh ok, running a port scan i didn't see those ports exposed so i assumed this way it could be achieved...

**Comment by frenck** [comment]
So, you didn't test this change either, as you would have learned this PR doesn't add or change anything, besides adding a bunch of fake port numbers to the UI.

The add-on runs on the host network, there is no port to forward or map.

**Comment by imbenwolf** [comment]
oh sorry i just wanted to open a conversation sort of like a feature request or but show that i am willing to program but just need to right input. now its not clear to me if its possible (since its running on the host network) or not and you just closed this pr since the code is not mergable. dont get me wrong, i knew that this is just symbolic. maybe we got off on the wrong foot - i want to ask for/help for exposing these ports. this commit was to illustrate what i mean better

**Comment by frenck** [comment]
The PR is mergeable but doesn't change a thing, it is possible, as it runs on the host network already.

> i knew that this is just symbolic

You don't help anybody with that, except wasting my time looking at stuff that doesn't make sense. I could have spent that on something that did have value.

**Comment by imbenwolf** [comment]
sorry, im just starting out contributing to open source after just working for companies all the time and got over excited and opened a pr with symbolic code without realizing it is wasting your time. i thought a issue would be more frustrating, as it doesnt show willingness to contribute. again, sorry. i love home assistant and wanted to make it better

**Comment by imbenwolf** [comment]
so do you want me to open an issue? because the problem is simply if i enable the https port in dns encryption i cannot access it

**Pull request closed without merging**
